GET http://127.0.0.1:8000/api/admin/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI2NDUyMTc4LCJpYXQiOjE3MjY0NTE4NzgsImp0aSI6ImJjMzg2ZTUzZjY4ZDQ0YTg4Zjg2NzRmMDIyN2I5YjhlIiwidXNlcl9pZCI6MTcsImlkIjoxNywicm9sZSI6ImVtcGxveWVlIiwiaXNfYWN0aXZlIjp0cnVlfQ.2G9gHsG4H3WGSgLFtTPBv7jzQXcRpSIq8Rg9u-kx5Ik
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/admin/admin_leave_requests/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI2NDczNjg4LCJpYXQiOjE3MjY0NzMzODgsImp0aSI6IjUyYjQ0Nzg3MDkyYjRjYWVhNDczMDMzNTdkYzU5M2U5IiwidXNlcl9pZCI6MjUsImlkIjoyNSwicm9sZSI6ImVtcGxveWVlIiwiaXNfYWN0aXZlIjp0cnVlfQ.tRBTb7kqe2G1dmqatFeqKxMmUwcoRudvcyx3CYGtQdU
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/admin/admin_leave_requests/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI2NDczNjg4LCJpYXQiOjE3MjY0NzMzODgsImp0aSI6IjUyYjQ0Nzg3MDkyYjRjYWVhNDczMDMzNTdkYzU5M2U5IiwidXNlcl9pZCI6MjUsImlkIjoyNSwicm9sZSI6ImVtcGxveWVlIiwiaXNfYWN0aXZlIjp0cnVlfQ.tRBTb7kqe2G1dmqatFeqKxMmUwcoRudvcyx3CYGtQdU
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/admin/user-leave-report/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI2NDc5MTk0LCJpYXQiOjE3MjY0Nzg4OTQsImp0aSI6Ijg5ZGFmZjI2Mjc5ZjQ3NGViMmViMWY2ZTlhNDJhMjFkIiwidXNlcl9pZCI6MjUsImlkIjoyNSwicm9sZSI6ImVtcGxveWVlIiwiaXNfYWN0aXZlIjp0cnVlfQ.MHLp2UZVc5VnH7EhMldYBohGJjwlyIj9VDUf-rkPqkk
Content-Type: application/json

