# Generated by Django 5.1.1 on 2024-09-16 04:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='leave_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
