# Generated by Django 5.1.1 on 2024-09-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_leave_date_remove_profile_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reason_not_approved',
            field=models.TextField(blank=True, null=True),
        ),
    ]
